# ruff: noqa: E501
"""Pure Codex config.toml adapter."""

from __future__ import annotations

import json
import tomllib

from mcp_trust.portability.errors import PortabilityInputError, safe_error_text
from mcp_trust.portability.models import (
    AuthRequirement,
    ChangeState,
    EnvironmentBinding,
    HeaderBinding,
    HttpTransport,
    InspectResult,
    NeutralConfig,
    Provenance,
    RenderResult,
    ScopePolicy,
    ServerIntent,
    StartupPolicy,
    StdioTransport,
    ValueSource,
    redact_host_args,
)
from mcp_trust.portability.report import build_report, change

from .base import note_unknown_fields, source_from_host_value

_DOC_URL = "https://learn.chatgpt.com/docs/extend/mcp?surface=cli"
_FORMAT = "config.toml current format (no published format version; docs as of 2026-08-11)"
_KNOWN = {
    "args",
    "auth",
    "bearer_token_env_var",
    "command",
    "cwd",
    "default_tools_approval_mode",
    "disabled_tools",
    "enabled",
    "enabled_tools",
    "env",
    "env_http_headers",
    "env_vars",
    "experimental_environment",
    "http_headers",
    "oauth_resource",
    "required",
    "scopes",
    "startup_timeout_ms",
    "startup_timeout_sec",
    "tool_timeout_sec",
    "tools",
    "url",
}


def _toml_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _toml_array(values: list[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def _toml_map(values: dict[str, str]) -> str:
    body = ", ".join(
        f"{_toml_string(key)} = {_toml_string(value)}" for key, value in sorted(values.items())
    )
    return "{ " + body + " }"


class CodexAdapter:
    host = "codex"
    format_version = _FORMAT

    def render(self, intent: NeutralConfig) -> RenderResult:
        lines = ["# Generated by mcp-trust portability studio; review before manual use."]
        changes = []
        for name, server in sorted(intent.servers.items()):
            lines.extend(["", f"[mcp_servers.{_toml_string(name)}]"])
            if isinstance(server.transport, StdioTransport):
                lines.append(f"command = {_toml_string(server.transport.command)}")
                lines.append(f"args = {_toml_array(server.transport.args)}")
                changes.append(
                    change(name, "transport", ChangeState.PRESERVED, "stdio transport preserved.")
                )
                if server.transport.cwd is not None:
                    lines.append(f"cwd = {_toml_string(server.transport.cwd)}")
                    changes.append(
                        change(
                            name,
                            "transport.cwd",
                            ChangeState.PRESERVED,
                            "Working directory preserved.",
                        )
                    )
                if server.environment:
                    env_names = sorted(item.name for item in server.environment)
                    lines.append(f"env_vars = {_toml_array(env_names)}")
                    changes.append(
                        change(
                            name,
                            "environment",
                            ChangeState.TRANSFORMED,
                            "Environment bindings rendered as Codex env_vars names; no values were emitted.",
                        )
                    )
            else:
                lines.append(f"url = {_toml_string(server.transport.url)}")
                changes.append(
                    change(
                        name, "transport", ChangeState.PRESERVED, "Streamable HTTP URL preserved."
                    )
                )
                env_headers: dict[str, str] = {}
                for header in server.transport.headers:
                    if header.value_from.kind == "environment":
                        env_headers[header.name] = header.value_from.key
                    else:
                        changes.append(
                            change(
                                name,
                                f"transport.headers.{header.name}",
                                ChangeState.UNSUPPORTED,
                                "Codex config has no host-prompt placeholder for this header; the header was omitted.",
                            )
                        )
                if env_headers:
                    lines.append(f"env_http_headers = {_toml_map(env_headers)}")
                    changes.append(
                        change(
                            name,
                            "transport.headers",
                            ChangeState.PRESERVED,
                            "Header-to-environment references preserved without secret values.",
                        )
                    )

            lines.append(f"enabled = {'true' if server.enabled else 'false'}")
            changes.append(change(name, "enabled", ChangeState.PRESERVED, "Enablement preserved."))
            if server.startup.required is not None:
                lines.append(f"required = {'true' if server.startup.required else 'false'}")
                changes.append(
                    change(
                        name,
                        "startup.required",
                        ChangeState.PRESERVED,
                        "Required-startup policy preserved.",
                    )
                )
            if server.startup.startup_timeout_seconds is not None:
                lines.append(f"startup_timeout_sec = {server.startup.startup_timeout_seconds:g}")
                changes.append(
                    change(
                        name,
                        "startup.startup_timeout_seconds",
                        ChangeState.PRESERVED,
                        "Startup timeout preserved in seconds.",
                    )
                )
            if server.startup.tool_timeout_seconds is not None:
                lines.append(f"tool_timeout_sec = {server.startup.tool_timeout_seconds:g}")
                changes.append(
                    change(
                        name,
                        "startup.tool_timeout_seconds",
                        ChangeState.PRESERVED,
                        "Tool timeout preserved in seconds.",
                    )
                )
            if server.tools.allow:
                lines.append(f"enabled_tools = {_toml_array(sorted(server.tools.allow))}")
                changes.append(
                    change(name, "tools.allow", ChangeState.PRESERVED, "Tool allowlist preserved.")
                )
            if server.tools.deny:
                lines.append(f"disabled_tools = {_toml_array(sorted(server.tools.deny))}")
                changes.append(
                    change(name, "tools.deny", ChangeState.PRESERVED, "Tool denylist preserved.")
                )
            if server.resources.allow or server.resources.deny:
                changes.append(
                    change(
                        name,
                        "resources",
                        ChangeState.WIDENED,
                        "Codex config does not expose a resource allow/deny list; resource scope would be broader.",
                    )
                )
            if server.auth.kind == "bearer" and server.auth.token is not None:
                if (
                    isinstance(server.transport, HttpTransport)
                    and server.auth.token.kind == "environment"
                ):
                    lines.append(f"bearer_token_env_var = {_toml_string(server.auth.token.key)}")
                    changes.append(
                        change(
                            name,
                            "auth",
                            ChangeState.PRESERVED,
                            "Bearer token environment reference preserved.",
                        )
                    )
                else:
                    changes.append(
                        change(
                            name,
                            "auth",
                            ChangeState.UNSUPPORTED,
                            "Bearer authentication could not be represented safely for this transport/source.",
                        )
                    )
            elif server.auth.kind == "oauth":
                if isinstance(server.transport, HttpTransport):
                    lines.append('auth = "oauth"')
                    if server.auth.scopes:
                        lines.append(f"scopes = {_toml_array(sorted(server.auth.scopes))}")
                    changes.append(
                        change(
                            name,
                            "auth",
                            ChangeState.PRESERVED,
                            "OAuth requirement and requested scopes preserved.",
                        )
                    )
                else:
                    changes.append(
                        change(
                            name,
                            "auth",
                            ChangeState.UNSUPPORTED,
                            "OAuth is not a Codex stdio transport setting.",
                        )
                    )
            elif server.auth.kind not in {"none", "headers"}:
                changes.append(
                    change(
                        name,
                        "auth",
                        ChangeState.UNKNOWN,
                        "Authentication requirement is not safely representable in Codex config.",
                    )
                )
            for field in server.unknown_semantics:
                changes.append(
                    change(
                        name,
                        f"unknown_semantics.{field}",
                        ChangeState.DROPPED,
                        "Named unknown host semantic cannot be emitted without its discarded source value.",
                    )
                )

        document = "\n".join(lines) + "\n"
        return RenderResult(
            document=document,
            report=build_report(
                operation="render",
                host=self.host,
                format_version=self.format_version,
                changes=changes,
            ),
        )

    def inspect(self, document: str) -> InspectResult:
        try:
            root = tomllib.loads(document)
        except (tomllib.TOMLDecodeError, UnicodeError) as exc:
            public_error = PortabilityInputError(f"invalid Codex TOML: {safe_error_text(exc)}")
        else:
            public_error = None
        if public_error is not None:
            raise public_error
        raw_servers = root.get("mcp_servers")
        if not isinstance(raw_servers, dict):
            raise PortabilityInputError("Codex input must contain an [mcp_servers] table")
        changes = []
        servers: dict[str, ServerIntent] = {}
        for name, raw_value in sorted(raw_servers.items()):
            if not isinstance(raw_value, dict):
                raise PortabilityInputError(f"Codex server {name!r} must be a table")
            raw = dict(raw_value)
            has_command = isinstance(raw.get("command"), str)
            has_url = isinstance(raw.get("url"), str)
            if has_command == has_url:
                raise PortabilityInputError(
                    f"Codex server {name!r} must contain exactly one of command or url"
                )
            if has_command:
                args, redactions = redact_host_args(list(raw.get("args") or []), server=name)
                changes.extend(redactions)
                transport = StdioTransport(command=raw["command"], args=args, cwd=raw.get("cwd"))
                changes.append(
                    change(name, "transport", ChangeState.PRESERVED, "stdio transport inspected.")
                )
            else:
                headers = []
                env_headers = raw.get("env_http_headers") or {}
                if not isinstance(env_headers, dict):
                    raise PortabilityInputError(
                        f"Codex server {name!r} env_http_headers must be a table"
                    )
                for header_name, env_name in sorted(env_headers.items()):
                    headers.append(
                        HeaderBinding(
                            name=str(header_name),
                            value_from=ValueSource(kind="environment", key=str(env_name)),
                        )
                    )
                    changes.append(
                        change(
                            name,
                            f"transport.headers.{header_name}",
                            ChangeState.PRESERVED,
                            "Header environment reference preserved.",
                        )
                    )
                literal_headers = raw.get("http_headers") or {}
                if not isinstance(literal_headers, dict):
                    raise PortabilityInputError(
                        f"Codex server {name!r} http_headers must be a table"
                    )
                for header_name, host_value in sorted(literal_headers.items()):
                    if str(header_name).lower() == "authorization" and raw.get(
                        "bearer_token_env_var"
                    ):
                        continue
                    headers.append(
                        HeaderBinding(
                            name=str(header_name),
                            value_from=source_from_host_value(
                                host_value,
                                fallback_key=f"HEADER_{header_name}",
                                server=name,
                                path=f"transport.headers.{header_name}",
                                changes=changes,
                            ),
                        )
                    )
                transport = HttpTransport(url=raw["url"], headers=headers)
                changes.append(
                    change(
                        name, "transport", ChangeState.PRESERVED, "Streamable HTTP URL inspected."
                    )
                )

            environment: dict[str, EnvironmentBinding] = {}
            env_names = raw.get("env_vars") or []
            if not isinstance(env_names, list):
                raise PortabilityInputError(f"Codex server {name!r} env_vars must be an array")
            for item in env_names:
                env_name = (
                    item
                    if isinstance(item, str)
                    else item.get("name")
                    if isinstance(item, dict)
                    else None
                )
                if env_name:
                    environment[str(env_name)] = EnvironmentBinding(
                        name=str(env_name),
                        value_from=ValueSource(kind="environment", key=str(env_name)),
                    )
            literal_env = raw.get("env") or {}
            if not isinstance(literal_env, dict):
                raise PortabilityInputError(f"Codex server {name!r} env must be a table")
            for env_name in sorted(literal_env):
                environment[str(env_name)] = EnvironmentBinding(
                    name=str(env_name),
                    value_from=ValueSource(kind="environment", key=str(env_name)),
                )
                changes.append(
                    change(
                        name,
                        f"environment.{env_name}",
                        ChangeState.TRANSFORMED,
                        "Literal environment value replaced by an environment-name reference; the original value was not retained.",
                    )
                )
            if environment:
                changes.append(
                    change(
                        name,
                        "environment",
                        ChangeState.PRESERVED,
                        "Environment key names preserved.",
                    )
                )

            auth = AuthRequirement()
            token_env = raw.get("bearer_token_env_var")
            if isinstance(token_env, str):
                auth = AuthRequirement(
                    kind="bearer",
                    required=True,
                    token=ValueSource(kind="environment", key=token_env),
                )
                changes.append(
                    change(
                        name,
                        "auth",
                        ChangeState.PRESERVED,
                        "Bearer token environment reference preserved.",
                    )
                )
            elif raw.get("auth") == "oauth" or raw.get("scopes"):
                auth = AuthRequirement(
                    kind="oauth",
                    required=True,
                    scopes=sorted(str(item) for item in raw.get("scopes") or []),
                )
                changes.append(
                    change(name, "auth", ChangeState.PRESERVED, "OAuth requirement inspected.")
                )
            elif raw.get("auth") == "chatgpt":
                auth = AuthRequirement(kind="unknown", required=False)
                changes.append(
                    change(
                        name,
                        "auth",
                        ChangeState.UNKNOWN,
                        "ChatGPT-session authentication has no neutral portable equivalent.",
                    )
                )

            if "enabled" not in raw:
                changes.append(
                    change(
                        name,
                        "enabled",
                        ChangeState.DEFAULTED,
                        "Codex default enabled=true applied.",
                    )
                )
            startup_seconds = raw.get("startup_timeout_sec")
            if startup_seconds is None and raw.get("startup_timeout_ms") is not None:
                startup_seconds = float(raw["startup_timeout_ms"]) / 1000
                changes.append(
                    change(
                        name,
                        "startup.startup_timeout_seconds",
                        ChangeState.TRANSFORMED,
                        "Milliseconds normalized to seconds.",
                    )
                )
            startup = StartupPolicy(
                startup_timeout_seconds=startup_seconds,
                tool_timeout_seconds=raw.get("tool_timeout_sec"),
                required=raw.get("required"),
            )
            unknown = note_unknown_fields(server=name, raw=raw, known=_KNOWN, changes=changes)
            servers[name] = ServerIntent(
                transport=transport,
                environment=[environment[key] for key in sorted(environment)],
                auth=auth,
                enabled=bool(raw.get("enabled", True)),
                tools=ScopePolicy(
                    allow=sorted(str(item) for item in raw.get("enabled_tools") or []),
                    deny=sorted(str(item) for item in raw.get("disabled_tools") or []),
                ),
                resources=ScopePolicy(),
                startup=startup,
                provenance=Provenance(
                    source_host="codex",
                    source_format=_FORMAT,
                    source_as_of="2026-08-11",
                    documentation_url=_DOC_URL,
                ),
                unknown_semantics=unknown,
            )
        intent = NeutralConfig(servers=servers)
        return InspectResult(
            intent=intent,
            report=build_report(
                operation="inspect",
                host=self.host,
                format_version=self.format_version,
                changes=changes,
            ),
        )
