"""Static catalog generator.

Reads the registry's stored servers and latest scans and writes a self-contained
static site:

- ``index.html``                       — the catalog table (``/``)
- ``ui/servers/<slug>/index.html``     — one detail page per server
- ``servers/<slug>/badge.json``        — one shields.io endpoint per server
- ``404.html``                         — generic not-found page

Paths mirror the absolute links the ``web`` renderers already emit, so on a
clean-URL host (Vercel) ``/ui/servers/<slug>`` and ``/servers/<slug>/badge.json``
resolve to these files with no rewriting.

HONESTY is enforced here, not left to the template: every page built from
demo/stub data carries a loud banner, and badges/grades are gated by
:func:`mcp_trust.core.provenance.classify`.
"""

from __future__ import annotations

import json
import shutil
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from mcp_trust.api.web import render_catalog, render_detail, render_not_found
from mcp_trust.core.models import TrustGrade
from mcp_trust.core.provenance import ScanProvenance, classify
from mcp_trust.site.badges import badge_payload
from mcp_trust.store.repository import ScanRepository, ServerRepository

# The loud label shown whenever any rendered grade is demo/stub data.
_DEMO_BANNER = (
    "DEMO DATA — Grades on this site were generated by the deterministic stub "
    "engine for demonstration, not by scanning real MCP servers. Do not rely on them."
)

# Subtrees the generator fully owns and rebuilds, so stale pages never linger.
# Everything else in the output dir (e.g. a user's vercel.json) is left untouched.
# Slug safety (no path separators / traversal) is enforced upstream by the
# Server model + repository, so the generator renders already-trusted slugs.
_MANAGED_DIRS = ("ui", "servers")


@dataclass(frozen=True)
class SiteBuild:
    """Result of one site build."""

    out_dir: Path
    pages: tuple[Path, ...]
    server_count: int
    scanned_count: int
    demo_count: int


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _clean_managed(out_dir: Path) -> None:
    """Remove generator-owned subtrees before a rebuild (orphan-page hygiene)."""
    for name in _MANAGED_DIRS:
        target = out_dir / name
        # Guard against a symlink at the managed path: rmtree on a symlinked dir
        # is platform-dependent (may delete the link target or crash). Only a
        # real directory we own is rebuilt.
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)


def generate_site(
    conn: sqlite3.Connection,
    out_dir: str | Path,
    *,
    base_url: str,
) -> SiteBuild:
    """Generate the static catalog from *conn* into *out_dir*.

    Parameters
    ----------
    conn:
        Open SQLite connection to the registry database (read-only access).
    out_dir:
        Destination directory. Created if absent. Generator-owned subtrees are
        rebuilt; unmanaged files are preserved.
    base_url:
        Absolute deployment base URL (no trailing slash needed) used to build
        shields.io badge-embed snippets, e.g. ``https://mcp-trust.example``.
    """
    out_dir = Path(out_dir)
    base_url = base_url.rstrip("/")
    server_repo = ServerRepository(conn)
    scan_repo = ScanRepository(conn)

    servers = server_repo.list()
    latest = scan_repo.latest_all()

    _clean_managed(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    pages: list[Path] = []
    server_count = 0
    scanned_count = 0
    demo_count = 0
    rows: list[dict] = []

    for srv in servers:
        scan = latest.get(srv.slug)
        provenance = classify(scan)
        server_count += 1
        if scan is not None:
            scanned_count += 1
        if provenance is ScanProvenance.DEMO:
            demo_count += 1

        grade = str(scan.grade) if scan else str(TrustGrade.UNSCANNED)
        rows.append(
            {
                "slug": srv.slug,
                "name": srv.name,
                "grade": grade,
                "transparency": str(scan.transparency) if scan else "",
                "composite": scan.risk.composite if scan else None,
                "scanned_at": scan.scanned_at.isoformat() if scan else "",
            }
        )

        page_banner = _DEMO_BANNER if provenance is ScanProvenance.DEMO else None
        detail_path = out_dir / "ui" / "servers" / srv.slug / "index.html"
        _write(detail_path, render_detail(srv, scan, base_url=base_url, banner=page_banner))
        pages.append(detail_path)

        badge_path = out_dir / "servers" / srv.slug / "badge.json"
        _write(badge_path, json.dumps(badge_payload(grade, provenance), indent=2) + "\n")
        pages.append(badge_path)

    index_path = out_dir / "index.html"
    _write(index_path, render_catalog(rows, banner=_DEMO_BANNER if demo_count else None))
    pages.append(index_path)

    notfound_path = out_dir / "404.html"
    _write(notfound_path, render_not_found("unknown"))
    pages.append(notfound_path)

    return SiteBuild(
        out_dir=out_dir,
        pages=tuple(pages),
        server_count=server_count,
        scanned_count=scanned_count,
        demo_count=demo_count,
    )
